name: ous
description: 岡山理科大学の非公式アプリ
publish_to: 'none' 
version: 2.3.5+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  url_launcher: ^6.3.1
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  settings_ui: ^2.0.2
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  google_sign_in: ^6.2.2
  path: ^1.9.0
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.3.4
  syncfusion_flutter_gauges: ^28.1.35
  package_info_plus: ^8.1.2
  fluttertoast: ^8.2.10
  sign_in_with_apple: ^6.1.4
  flutter_native_splash: ^2.4.3
  flutter_overboard: ^3.1.3
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  flutter_speed_dial: ^7.0.0
  flutter_launcher_icons: ^0.14.2
  slide_to_act: ^2.0.2
  markdown_widget: ^2.3.2
  dio: ^5.7.0
  firebase_remote_config: ^5.4.2
  firebase_analytics: ^11.4.4
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  fl_chart: ^0.70.0
  share_plus: ^10.1.3
  font_awesome_flutter: ^10.8.0
  screenshot: ^3.0.0
  google_fonts: ^6.2.1
  xml: ^6.5.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.5
  html: ^0.15.5
  webview_flutter: ^4.10.0
  supabase_flutter: ^2.8.2
  flutter_dotenv: ^5.2.1
  image_cropper: ^8.1.0
  flutter_local_notifications: ^18.0.1
  rotated_corner_decoration: ^2.1.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  badges: ^3.1.2
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: 4.1.2
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7  
  json_serializable: ^6.9.0
  slang_build_runner: ^4.4.0
  pedantic_mono: any
  flutter_gen_runner: ^5.8.0
  import_sorter: ^4.6.0
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icon/

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icon/icon.png'
  color_dark: '#202124'
  image_dark: 'assets/icon/icon_dark.png'
  fullscreen: false
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/icon/icon.png'
    icon_background_color_dark: '#202124'
    image_dark: 'assets/icon/icon_dark.png'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
